<a href="https://colab.research.google.com/github/anitakumar/ml/blob/main/decisiontrees.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
#

In [3]:
df=pd.read_csv('balance-scale.data',sep=',')

In [4]:
df.head()

Class Name  Left weight  Left distance  Right weight  Right distance
0          B            1              1             1               1
1          R            1              1             1               2
2          R            1              1             1               3
3          R            1              1             1               4
4          R            1              1             1               5

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Class Name      625 non-null    object
 1   Left weight     625 non-null    int64 
 2   Left distance   625 non-null    int64 
 3   Right weight    625 non-null    int64 
 4   Right distance  625 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 24.5+ KB


In [6]:
#predict class name
df['Class Name'].value_counts()

Class Name
R    288
L    288
B     49
Name: count, dtype: int64

In [7]:
df.isnull().sum()

Class Name        0
Left weight       0
Left distance     0
Right weight      0
Right distance    0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
X=df.drop('Class Name',axis=1)
y=df['Class Name']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [10]:
clf_model=DecisionTreeClassifier(criterion='gini',random_state=42,max_depth=3,min_samples_leaf=5)
clf_model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=42)

In [11]:
DecisionTreeClassifier(max_depth=3,min_samples_leaf=5,random_state=42)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=42)

In [12]:
y_pred=clf_model.predict(X_test)

In [13]:
# prompt: confusion matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)


[[ 0 12  2]
 [ 0 78 12]
 [ 0 16 68]]


In [14]:
# prompt: conclusion from theconfusion metrics

print("Confusion Matrix:")
print(cm)

# Analyze the confusion matrix
TP = cm[0][0]  # True Positives (correctly predicted 'L')
FP = cm[0][1]  # False Positives (incorrectly predicted 'R')
FN = cm[1][0]  # False Negatives (incorrectly predicted 'L')
TN = cm[1][1]  # True Negatives (correctly predicted 'R')


accuracy = (TP + TN) / (TP + FP + FN + TN)
precision = TP / (TP + FP)
recall = TP / (TP + FN)
f1_score = 2 * (precision * recall) / (precision + recall)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-Score: {f1_score}")


print("\nConclusion:")
print("The model's performance can be evaluated based on the confusion matrix and derived metrics.")
print("Accuracy represents the overall correctness of the model.")
print("Precision indicates the proportion of correctly predicted positive instances among all predicted positive instances.")
print("Recall highlights the proportion of correctly predicted positive instances among all actual positive instances.")
print("F1-score balances precision and recall, offering a comprehensive measure of model performance.")

# Further analysis can be done based on the specific context and requirements of the problem.


Confusion Matrix:
[[ 0 12  2]
 [ 0 78 12]
 [ 0 16 68]]
Accuracy: 0.8666666666666667
Precision: 0.0
Recall: nan
F1-Score: nan

Conclusion:
The model's performance can be evaluated based on the confusion matrix and derived metrics.
Accuracy represents the overall correctness of the model.
Precision indicates the proportion of correctly predicted positive instances among all predicted positive instances.
Recall highlights the proportion of correctly predicted positive instances among all actual positive instances.
F1-score balances precision and recall, offering a comprehensive measure of model performance.


In [15]:
target=df['Class Name']
feather_names=X.columns

In [16]:
# prompt: export tree

from sklearn.tree import export_graphviz
import graphviz

dot_data = export_graphviz(clf_model, out_file=None,
                         feature_names=feather_names,
                         class_names=target.unique(),
                         filled=True, rounded=True,
                         special_characters=True)
graph = graphviz.Source(dot_data)
graph.render("decision_tree")


'decision_tree.pdf'